In [1]:
import pickle

with open("/share/nas169/jethrowang/DB/pkl/train_both.pkl", "rb") as f:
    data = pickle.load(f)

In [2]:
type(data)

pandas.core.frame.DataFrame

In [5]:
data.head()

,wav_label,wav,text,duration,label,type,phoneme,wav_phoneme,pIndex,wav_pIndex,g2p_embed,dist
0,that is to say,/share/nas169/albertali/Libriphrase/LibriPhras...,that is to say,0.71,1,diffspk_easyneg,"[TH, AE1, T, , IH1, Z, , T, OW1, , S, EY1]","[TH, AE1, T, , IH1, Z, , T, OW1, , S, EY1]","[58, 5, 57, 71, 36, 69, 71, 57, 48, 71, 55, 30]","[58, 5, 57, 71, 36, 69, 71, 57, 48, 71, 55, 30]","[[0.9997743964195251, 0.10310205817222595, 0.6...",1.0
1,that is to say,/share/nas169/albertali/Libriphrase/LibriPhras...,that is to say,0.76,1,diffspk_easyneg,"[TH, AE1, T, , IH1, Z, , T, OW1, , S, EY1]","[TH, AE1, T, , IH1, Z, , T, OW1, , S, EY1]","[58, 5, 57, 71, 36, 69, 71, 57, 48, 71, 55, 30]","[58, 5, 57, 71, 36, 69, 71, 57, 48, 71, 55, 30]","[[0.9997743964195251, 0.10310205817222595, 0.6...",1.0
2,that is to say,/share/nas169/albertali/Libriphrase/LibriPhras...,that is to say,0.76,1,diffspk_easyneg,"[TH, AE1, T, , IH1, Z, , T, OW1, , S, EY1]","[TH, AE1, T, , IH1, Z, , T, OW1, , S, EY1]","[58, 5, 57, 71, 36, 69, 71, 57, 48, 71, 55, 30]","[58, 5, 57, 71, 36, 69, 71, 57, 48, 71, 55, 30]","[[0.9997743964195251, 0.10310205817222595, 0.6...",1.0
3,that is to say,/share/nas169/albertali/Libriphrase/LibriPhras...,that is to say,0.82,1,diffspk_easyneg,"[TH, AE1, T, , IH1, Z, , T, OW1, , S, EY1]","[TH, AE1, T, , IH1, Z, , T, OW1, , S, EY1]","[58, 5, 57, 71, 36, 69, 71, 57, 48, 71, 55, 30]","[58, 5, 57, 71, 36, 69, 71, 57, 48, 71, 55, 30]","[[0.9997743964195251, 0.10310205817222595, 0.6...",1.0
4,that is to say,/share/nas169/albertali/Libriphrase/LibriPhras...,that is to say,0.82,1,diffspk_easyneg,"[TH, AE1, T, , IH1, Z, , T, OW1, , S, EY1]","[TH, AE1, T, , IH1, Z, , T, OW1, , S, EY1]","[58, 5, 57, 71, 36, 69, 71, 57, 48, 71, 55, 30]","[58, 5, 57, 71, 36, 69, 71, 57, 48, 71, 55, 30]","[[0.9997743964195251, 0.10310205817222595, 0.6...",1.0

In [6]:
data.columns

Index(['wav_label', 'wav', 'text', 'duration', 'label', 'type', 'phoneme',
       'wav_phoneme', 'pIndex', 'wav_pIndex', 'g2p_embed', 'dist'],
      dtype='object')

In [7]:
data.dtypes

wav_label       object
wav             object
text            object
duration       float64
label           object
type            object
phoneme         object
wav_phoneme     object
pIndex          object
wav_pIndex      object
g2p_embed       object
dist           float64
dtype: object

In [8]:
data.describe()

            duration           dist
count  730296.000000  730296.000000
mean        0.648327       0.833826
std         0.137867       0.277905
min         0.500000       0.000000
25%         0.550000       0.750000
50%         0.610000       1.000000
75%         0.710000       1.000000
max         1.990000       1.000000

In [9]:
data.shape

(730296, 12)

In [10]:
data.head(100)

,wav_label,wav,text,duration,label,type,phoneme,wav_phoneme,pIndex,wav_pIndex,g2p_embed,dist
0,that is to say,/share/nas169/albertali/Libriphrase/LibriPhras...,that is to say,0.71,1,diffspk_easyneg,"[TH, AE1, T, , IH1, Z, , T, OW1, , S, EY1]","[TH, AE1, T, , IH1, Z, , T, OW1, , S, EY1]","[58, 5, 57, 71, 36, 69, 71, 57, 48, 71, 55, 30]","[58, 5, 57, 71, 36, 69, 71, 57, 48, 71, 55, 30]","[[0.9997743964195251, 0.10310205817222595, 0.6...",1.000000
1,that is to say,/share/nas169/albertali/Libriphrase/LibriPhras...,that is to say,0.76,1,diffspk_easyneg,"[TH, AE1, T, , IH1, Z, , T, OW1, , S, EY1]","[TH, AE1, T, , IH1, Z, , T, OW1, , S, EY1]","[58, 5, 57, 71, 36, 69, 71, 57, 48, 71, 55, 30]","[58, 5, 57, 71, 36, 69, 71, 57, 48, 71, 55, 30]","[[0.9997743964195251, 0.10310205817222595, 0.6...",1.000000
2,that is to say,/share/nas169/albertali/Libriphrase/LibriPhras...,that is to say,0.76,1,diffspk_easyneg,"[TH, AE1, T, , IH1, Z, , T, OW1, , S, EY1]","[TH, AE1, T, , IH1, Z, , T, OW1, , S, EY1]","[58, 5, 57, 71, 36, 69, 71, 57, 48, 71, 55, 30]","[58, 5, 57, 71, 36, 69, 71, 57, 48, 71, 55, 30]","[[0.9997743964195251, 0.10310205817222595, 0.6...",1.000000
3,that is to say,/share/nas169/albertali/Libriphrase/LibriPhras...,that is to say,0.82,1,diffspk_easyneg,"[TH, AE1, T, , IH1, Z, , T, OW1, , S, EY1]","[TH, AE1, T, , IH1, Z, , T, OW1, , S, EY1]","[58, 5, 57, 71, 36, 69, 71, 57, 48, 71, 55, 30]","[58, 5, 57, 71, 36, 69, 71, 57, 48, 71, 55, 30]","[[0.9997743964195251, 0.10310205817222595, 0.6...",1.000000
4,that is to say,/share/nas169/albertali/Libriphrase/LibriPhras...,that is to say,0.82,1,diffspk_easyneg,"[TH, AE1, T, , IH1, Z, , T, OW1, , S, EY1]","[TH, AE1, T, , IH1, Z, , T, OW1, , S, EY1]","[58, 5, 57, 71, 36, 69, 71, 57, 48, 71, 55, 30]","[58, 5, 57, 71, 36, 69, 71, 57, 48, 71, 55, 30]","[[0.9997743964195251, 0.10310205817222595, 0.6...",1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
95,that is to say,/share/nas169/albertali/Libriphrase/LibriPhras...,that was to sail,0.76,0,diffspk_hardneg,"[TH, AE1, T, , W, AA1, Z, , T, OW1, , S, EY...","[TH, AE1, T, , IH1, Z, , T, OW1, , S, EY1]","[58, 5, 57, 71, 67, 2, 69, 71, 57, 48, 71, 55,...","[58, 5, 57, 71, 36, 69, 71, 57, 48, 71, 55, 30]","[[0.9997743964195251, 0.10310205817222595, 0.6...",0.800000
96,that is to say,/share/nas169/albertali/Libriphrase/LibriPhras...,that is to be,0.82,0,diffspk_hardneg,"[TH, AE1, T, , IH1, Z, , T, OW1, , B, IY1]","[TH, AE1, T, , IH1, Z, , T, OW1, , S, EY1]","[58, 5, 57, 71, 36, 69, 71, 57, 48, 71, 19, 39]","[58, 5, 57, 71, 36, 69, 71, 57, 48, 71, 55, 30]","[[0.9997743964195251, 0.10310205817222595, 0.6...",0.814815
97,that is to say,/share/nas169/albertali/Libriphrase/LibriPhras...,that is to be,0.76,0,diffspk_hardneg,"[TH, AE1, T, , IH1, Z, , T, OW1, , B, IY1]","[TH, AE1, T, , IH1, Z, , T, OW1, , S, EY1]","[58, 5, 57, 71, 36, 69, 71, 57, 48, 71, 19, 39]","[58, 5, 57, 71, 36, 69, 71, 57, 48, 71, 55, 30]","[[0.9997743964195251, 0.10310205817222595, 0.6...",0.814815
98,that is to say,/share/nas169/albertali/Libriphrase/LibriPhras...,that is to be,0.71,0,diffspk_hardneg,"[TH, AE1, T, , IH1, Z, , T, OW1, , B, IY1]","[TH, AE1, T, , IH1, Z, , T, OW1, , S, EY1]","[58, 5, 57, 71, 36, 69, 71, 57, 48, 71, 19, 39]","[58, 5, 57, 71, 36, 69, 71, 57, 48, 71, 55, 30]","[[0.9997743964195251, 0.10310205817222595, 0.6...",0.814815
99,that is to say,/share/nas169/albertali/Libriphrase/LibriPhras...,that is to say,0.71,1,diffspk_positive,"[TH, AE1, T, , IH1, Z, , T, OW1, , S, EY1]","[TH, AE1, T, , IH1, Z, , T, OW1, , S, EY1]","[58, 5, 57, 71, 36, 69, 71, 57, 48, 71, 55, 30]","[58, 5, 57, 71, 36, 69, 71, 57, 48, 71, 55, 30]","[[0.9997743964195251, 0.10310205817222595, 0.6...",1.000000

In [19]:
data.to_csv('/share/nas169/jethrowang/DB/csv/train_both.csv', index=False)

In [20]:
data.iloc[80:90]

,wav,text,duration,label,phoneme,pIndex,g2p_embed
80,/share/nas169/albertali/Zero-shot-phonmatchnet...,hey android,0.925125,1,"[HH, EY1, , AE1, N, D, R, OY2, D]","[34, 30, 71, 5, 45, 21, 54, 52, 21]","[[-0.8383702039718628, 0.8358403444290161, 0.7..."
81,/share/nas169/albertali/Zero-shot-phonmatchnet...,hey snapdragon,0.925125,0,"[HH, EY1, , S, N, AE1, P, D, R, AE2, G, AH0, N]","[34, 30, 71, 55, 45, 5, 53, 21, 54, 6, 33, 7, 45]","[[-0.8383702039718628, 0.8358403444290161, 0.7..."
82,/share/nas169/albertali/Zero-shot-phonmatchnet...,hi galaxy,0.925125,0,"[HH, AY1, , G, AE1, L, AH0, K, S, IY0]","[34, 17, 71, 33, 5, 43, 7, 42, 55, 38]","[[-0.17809045314788818, 0.9817915558815002, 0...."
83,/share/nas169/albertali/Zero-shot-phonmatchnet...,hi lumina,0.925125,0,"[HH, AY1, , L, UW0, M, IY1, N, AH0]","[34, 17, 71, 43, 63, 44, 39, 45, 7]","[[-0.17809045314788818, 0.9817915558815002, 0...."
84,/share/nas169/albertali/Zero-shot-phonmatchnet...,hey android,0.829937,1,"[HH, EY1, , AE1, N, D, R, OY2, D]","[34, 30, 71, 5, 45, 21, 54, 52, 21]","[[-0.8383702039718628, 0.8358403444290161, 0.7..."
85,/share/nas169/albertali/Zero-shot-phonmatchnet...,hey snapdragon,0.829937,0,"[HH, EY1, , S, N, AE1, P, D, R, AE2, G, AH0, N]","[34, 30, 71, 55, 45, 5, 53, 21, 54, 6, 33, 7, 45]","[[-0.8383702039718628, 0.8358403444290161, 0.7..."
86,/share/nas169/albertali/Zero-shot-phonmatchnet...,hi galaxy,0.829937,0,"[HH, AY1, , G, AE1, L, AH0, K, S, IY0]","[34, 17, 71, 33, 5, 43, 7, 42, 55, 38]","[[-0.17809045314788818, 0.9817915558815002, 0...."
87,/share/nas169/albertali/Zero-shot-phonmatchnet...,hi lumina,0.829937,0,"[HH, AY1, , L, UW0, M, IY1, N, AH0]","[34, 17, 71, 43, 63, 44, 39, 45, 7]","[[-0.17809045314788818, 0.9817915558815002, 0...."
88,/share/nas169/albertali/Zero-shot-phonmatchnet...,hey android,0.818937,1,"[HH, EY1, , AE1, N, D, R, OY2, D]","[34, 30, 71, 5, 45, 21, 54, 52, 21]","[[-0.8383702039718628, 0.8358403444290161, 0.7..."
89,/share/nas169/albertali/Zero-shot-phonmatchnet...,hey snapdragon,0.818937,0,"[HH, EY1, , S, N, AE1, P, D, R, AE2, G, AH0, N]","[34, 30, 71, 55, 45, 5, 53, 21, 54, 6, 33, 7, 45]","[[-0.8383702039718628, 0.8358403444290161, 0.7..."